language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t digitalcitadel/digitalcitadel -f Dockerfile-main .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
after_success:
  - docker push digitalcitadel/digitalcitadel
deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-central-1
  app:  digital citadel
  env: DigitalCitadel-env
  bucket_name: elasticbeanstalk-eu-central-1-817711046507
  bucket_path: digitalcitadel
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
