language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t digitalcitadel/digitalcitadel -f Dockerfile-main .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
